Traceback (most recent call last):
  File "lddmm.py", line 239, in <module>
    v, Phi0, Phi1, J0, J1=LDDMM(i0, i1, T = 20, maxiter = 10, sigma = 0.1, alpha = 1, gamma = 1, lr = 0.001)
  File "lddmm.py", line 196, in LDDMM
    dJ0 = _image_grad(J0)
  File "lddmm.py", line 145, in _image_grad
    dJ0 = cp.empty((T, 3, nx, ny, nz), dtype = cp.float64)
  File "/usr/local/lib/python3.7/dist-packages/cupy/_creation/basic.py", line 22, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 138, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 578, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1250, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1271, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 939, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 959, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1210, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 6,635,520,000 bytes (allocated so far: 32,573,952,512 bytes).
